[2025-06-23 13:04:34,940] 127 __init__.py - INFO - Loaded config from Config_Yaml/config_path.yaml
[2025-06-23 13:04:34,940] 99 Experiment_Tracking_Prediction.py - INFO - MLflow tracking URI set to: https://dagshub.com/anp102618/ml_churn_prediction_mlops.mlflow
[2025-06-23 13:04:34,980] 127 __init__.py - INFO - Loaded config from Config_Yaml\tuned_models.yaml
[2025-06-23 13:04:34,980] 115 Experiment_Tracking_Prediction.py - INFO - Using model: XGBClassifier with params: {'colsample_bytree': 1.0, 'gamma': 0, 'learning_rate': 0.1, 'max_depth': 6, 'n_estimators': 200, 'reg_alpha': 0.1, 'reg_lambda': 1.5, 'subsample': 0.8, 'tree_method': 'hist'}
[2025-06-23 13:04:37,846] 159 Experiment_Tracking_Prediction.py - INFO - Started MLflow run: 4fd49bc9016b4ad79cd1c5fa6e256cb3
[2025-06-23 13:04:38,938] 207 Experiment_Tracking_Prediction.py - ERROR - [UnhandledException] name 'model_copy_path' is not defined
Traceback (most recent call last):
  File "D:\ml_churn_prediction_mlops\src\Experiment_Tracking_Prediction.py", line 172, in execute_mlflow_steps
    joblib.dump(model, model_copy_path)
NameError: name 'model_copy_path' is not defined. Did you mean: 'model_save_path'?
